-- PhoneMail mail service: initial schema (internal mail).
-- See "PhoneMail — Mail Service Spec", section 5.

CREATE EXTENSION IF NOT EXISTS ltree;

-- ---------------------------------------------------------------------------
-- Users and aliases (written by the API service; read by the mail service)
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    phone         text NOT NULL UNIQUE CHECK (phone ~ '^\+[0-9]{10,15}$'),   -- E.164, e.g. +919876543210
    -- Local part of the main address (<phone_local>@<domain>): the last 10 digits.
    phone_local   text GENERATED ALWAYS AS (right(phone, 10)) STORED UNIQUE,
    display_name  text NOT NULL DEFAULT '',
    language      text NOT NULL DEFAULT 'en',
    avatar_url    text NOT NULL DEFAULT '',
    password_hash text,
    has_push      boolean NOT NULL DEFAULT false,   -- false => SMS alerts
    created_via   text NOT NULL DEFAULT 'web'
                  CHECK (created_via IN ('ivr', 'sms', 'portal', 'web', 'mobile'))
);

CREATE TABLE aliases (
    alias   text PRIMARY KEY CHECK (alias = lower(alias) AND alias LIKE '%@%'),
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX aliases_user_idx ON aliases (user_id);

-- ---------------------------------------------------------------------------
-- Conversations (chats) and groups
-- ---------------------------------------------------------------------------

CREATE TABLE conversations (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind             text NOT NULL CHECK (kind IN ('direct', 'group')),
    name             text,
    participant_hash text NOT NULL,           -- sha256 of sorted current member ids
    created_by       bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CHECK ((kind = 'direct' AND name IS NULL)
        OR (kind = 'group'  AND name IS NOT NULL AND length(btrim(name)) > 0))
);
-- The same two people always share one direct chat.
CREATE UNIQUE INDEX conversations_direct_uniq ON conversations (participant_hash) WHERE kind = 'direct';
-- The same people may have several groups, but only one per name.
CREATE UNIQUE INDEX conversations_group_uniq  ON conversations (participant_hash, name) WHERE kind = 'group';

CREATE TABLE conversation_participants (
    conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    user_id         bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role            text NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
    joined_at       timestamptz NOT NULL DEFAULT now(),
    left_at         timestamptz,              -- NULL = current member
    PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX conversation_participants_user_idx ON conversation_participants (user_id) WHERE left_at IS NULL;

-- Each user's view of each chat: this table IS the Home screen.
CREATE TABLE user_conversations (
    user_id         bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    last_message_at timestamptz NOT NULL DEFAULT now(),
    last_message_id bigint,                   -- no FK: the message may be cleaned up later
    snippet         text NOT NULL DEFAULT '',
    unread_count    integer NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
    has_attachments boolean NOT NULL DEFAULT false,
    favourite_count integer NOT NULL DEFAULT 0 CHECK (favourite_count >= 0),
    hidden          boolean NOT NULL DEFAULT false,
    PRIMARY KEY (user_id, conversation_id)
);
CREATE INDEX user_conversations_home_idx
    ON user_conversations (user_id, last_message_at DESC, conversation_id DESC) WHERE NOT hidden;

-- ---------------------------------------------------------------------------
-- Messages (stored once, never edited)
-- ---------------------------------------------------------------------------

CREATE TABLE messages (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id         bigint NOT NULL REFERENCES users (id),
    subject           text NOT NULL DEFAULT '',
    body_text         text NOT NULL DEFAULT '',
    body_html         text NOT NULL DEFAULT '',
    snippet           text NOT NULL DEFAULT '',
    parent_id         bigint REFERENCES messages (id),
    root_id           bigint NOT NULL REFERENCES messages (id),
    path              ltree NOT NULL,
    depth             integer NOT NULL DEFAULT 0,
    forwarded_from_id bigint REFERENCES messages (id) ON DELETE SET NULL,
    has_attachments   boolean NOT NULL DEFAULT false,
    message_id_header text NOT NULL UNIQUE,
    sent_at           timestamptz NOT NULL DEFAULT now(),
    search            tsvector GENERATED ALWAYS AS
                      (to_tsvector('simple', subject || ' ' || body_text)) STORED
);
-- Reply once per person: at most one reply by each sender under any message.
CREATE UNIQUE INDEX messages_reply_once ON messages (parent_id, sender_id) WHERE parent_id IS NOT NULL;
CREATE INDEX messages_thread_idx ON messages (root_id, path);
CREATE INDEX messages_path_gist  ON messages USING gist (path);
CREATE INDEX messages_search_idx ON messages USING gin (search);

CREATE TABLE message_recipients (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    kind       text NOT NULL CHECK (kind IN ('to', 'cc', 'bcc')),
    user_id    bigint REFERENCES users (id),
    group_id   bigint REFERENCES conversations (id),
    CHECK (num_nonnulls(user_id, group_id) = 1)
);
CREATE UNIQUE INDEX message_recipients_one_to ON message_recipients (message_id) WHERE kind = 'to';
CREATE INDEX message_recipients_message_idx ON message_recipients (message_id);

-- ---------------------------------------------------------------------------
-- Each user's pointers to messages, with their own flags
-- ---------------------------------------------------------------------------

CREATE TABLE mailbox (
    user_id         bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    message_id      bigint NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    folder          text NOT NULL DEFAULT 'inbox' CHECK (folder IN ('inbox', 'spam', 'trash')),
    is_read         boolean NOT NULL DEFAULT false,
    is_favourite    boolean NOT NULL DEFAULT false,
    is_replied      boolean NOT NULL DEFAULT false,
    is_mine         boolean NOT NULL DEFAULT false,
    received_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    PRIMARY KEY (user_id, message_id, conversation_id)
);
CREATE INDEX mailbox_chat_idx   ON mailbox (user_id, conversation_id, received_at DESC, message_id DESC);
CREATE INDEX mailbox_folder_idx ON mailbox (user_id, folder, received_at DESC);
CREATE INDEX mailbox_message_idx ON mailbox (message_id);

-- ---------------------------------------------------------------------------
-- Drafts (user-owned; never in messages) and attachments
-- ---------------------------------------------------------------------------

CREATE TABLE drafts (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    conversation_id bigint REFERENCES conversations (id) ON DELETE SET NULL,
    parent_id       bigint REFERENCES messages (id) ON DELETE SET NULL,
    recipients      jsonb NOT NULL DEFAULT '{}',   -- {"to":{...},"cc":[...],"bcc":[...]}
    subject         text NOT NULL DEFAULT '',
    body_text       text NOT NULL DEFAULT '',
    body_html       text NOT NULL DEFAULT '',
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX drafts_user_idx ON drafts (user_id, updated_at DESC);

CREATE TABLE attachments (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id   bigint REFERENCES messages (id) ON DELETE CASCADE,
    draft_id     bigint REFERENCES drafts (id) ON DELETE CASCADE,
    filename     text NOT NULL,
    content_type text NOT NULL DEFAULT 'application/octet-stream',
    size_bytes   bigint NOT NULL,
    sha256       text NOT NULL,
    storage_path text NOT NULL,
    CHECK (num_nonnulls(message_id, draft_id) = 1)
);
CREATE INDEX attachments_message_idx ON attachments (message_id);
CREATE INDEX attachments_draft_idx   ON attachments (draft_id);
CREATE INDEX attachments_path_idx    ON attachments (storage_path);
